services:
  react-app:
    image: docker-demo
    ports:
      - 3000:3000
  redis:
    image: redis
  geoserver:
    image: kartoza/geoserver
    ports:
      - 8080:8080
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=password1234
    postgis:
      image: postgis/postgis
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=password